import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import { CartProvider } from "../components/CartContext";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Figma Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <CartProvider>
        {children}
        </CartProvider>
        <Footer />
      </body>
    </html>
   

  );
}

// // export default function Layout({ children }: { children: React.ReactNode }) {
// //   return (
// //     <CartProvider>
// //       <html lang="en">
// //         <body>
// //           {children}
// //         </body>
// //       </html>
// //     </CartProvider>
// //   );
// }